name: Deploy to cPanel

on:
  push:
    branches:
      - main  # or the branch you want to deploy from

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Specify your Node.js version

      # Install dependencies
      - name: Install dependencies
        run: |
          npm install

      # Build the project (if applicable, adjust based on your build tool)
      - name: Build project
        run: |
          npm run build

      # Deploy to cPanel using FTP
      - name: Deploy to cPanel
        uses: SamKirkland/FTP-Deploy-Action@v4
        with:
          host: ${{ secrets.CPANEL_FTP_HOST }}
          username: ${{ secrets.CPANEL_FTP_USERNAME }}
          password: ${{ secrets.CPANEL_FTP_PASSWORD }}
          local-dir: './build'  # Adjust based on your build output directory
          remote-dir: '/public_html'  # Adjust based on where you want to deploy

      # Optional: Notify deployment status
      - name: Notify deployment status
        run: |
          echo "Deployment to cPanel completed successfully."
